name: Deploy to VPS (GHCR)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Login v√†o GHCR (D√πng Token c√≥ s·∫µn c·ªßa GitHub Action, KH√îNG C·∫¶N SECRET)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Build & Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          # L∆∞u √Ω: github.repository_owner s·∫Ω l·∫•y t√™n user github c·ªßa b·∫°n
          tags: ghcr.io/${{ github.repository_owner }}/awd-g04-backend:latest

      # 3. Build & Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/awd-g04-frontend:latest
          # üëá B∆°m IP VPS v√†o l√∫c build ƒë·ªÉ React g·ªçi ƒë√∫ng API
          build-args: |
            VITE_API_URL=http://${{ secrets.VPS_IP }}:3000
            VITE_GOOGLE_CLIENT_ID=dummy_id_chua_can_thiet
            VITE_GOOGLE_REDIRECT_URI=http://${{ secrets.VPS_IP }}/login/oauth/google/callback

      # 4. Copy file docker-compose l√™n VPS
      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml"
          target: "/root/awd-g04/"

      # 5. SSH v√†o VPS v√† ch·∫°y
      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/awd-g04
            # ƒê·ªïi t√™n file
            mv docker-compose.prod.yml docker-compose.yml
            
            # K√©o Image m·ªõi nh·∫•t t·ª´ GHCR v·ªÅ
            docker compose pull
            
            # Kh·ªüi ƒë·ªông l·∫°i (Down tr∆∞·ªõc cho ch·∫Øc ƒÉn v√¨ ƒë·ªïi port/c·∫•u h√¨nh)
            docker compose down
            docker compose up -d
            
            # X√≥a image r√°c
            docker image prune -f